### ISSUE TITLE
v 0.3 milestones

### ISSUE THREAD

**Issue by jakevdp** [jakevdp/mpld3#278]
I think it's time to consider what milestones we want to hit for the 0.3 release. Here are a couple things I think should be doable with a bit of concerted effort:

- [ ] fixed tick locations. This should also fix the issue with colorbar labels being off
- [ ] mathjax support. Though this may take some doing...
- [ ] bar plot tooltips

ping @aflaxman, @danielballan – feel free to add to this if there are other things that seem doable in the short-term. Once we have a set of features in mind, perhaps we can do an organized push to try to address them. Thanks all!

**Comment by danielballan** [comment]
I think those are good goals. I edited your comment, adding links to the relevant issues.

I am still interested in #14. I finished my PhD last month -- hence my general disappearance since SciPy -- but I'm back!

**Comment by jakevdp** [comment]
@danielballan – awesome, congrats! What's next for you?

**Comment by danielballan** [comment]
@jakevdp I'm sitting across from @tacaswell at Brookhaven National Lab, getting ready for a firehose of X-ray data for NSLS-II.

**Comment by trschell** [comment]
Jake, does your first goal include resolving issue #247 ? That would be huge for me. Thanks!

**Comment by jakevdp** [comment]
@trschell – yes it does.

**Comment by aflaxman** [comment]
Thanks for starting this conversation.  I found some notes I made on this matter a month or two ago.  The big issues I would like to address are:

* streamline visual tests (and automate if possible)
* curate the gallery
** plugins as a separate section, grouped by visual information-seeking mantra (overview, zoom-and-filter, details-on-demand)
* make animated transitions easy

The key bug/features on my list are:
* mathjax / multiline text (including dates as ticks)
* responsive plots
* axvline
* text fonts
* spines and minor gridlines
* inverted axes
* second axes (is this an issue?  i can't read my notes on it...)
* legends
* background colors
* hexbin bug
* drawstyle for plots

**Comment by jakevdp** [comment]
Thanks Abie.

I think a lot of those are doable, but ``axvline`` will require a *significant* amount of effort. Mixed transforms will be very, very difficult to implement. You could probably monkey-patch the code to work in certain situations, but that's just digging a hole that would be hard to get out of later.

**Comment by tacaswell** [comment]
@jakevdp Is the issue getting the information _out_ of mpl or getting it _into_ d3?

**Comment by jakevdp** [comment]
The issue is that ``axvline`` creates a mixed transform, and the javascript side of ``mpld3`` would have to be essentially rewritten to correctly handle mixed transforms.
